# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 1082)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        MainWindow.setFont(font)
        MainWindow.setMouseTracking(True)
        MainWindow.setToolTipDuration(-2)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"}\n"
"\n"
"\n"
"\n"
"")
        MainWindow.setIconSize(QtCore.QSize(24, 24))
        MainWindow.setAnimated(True)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("QWidget {\n"
"    background: #FFFFFF;\n"
"}\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.videoButton = QtWidgets.QPushButton(self.centralwidget)
        self.videoButton.setGeometry(QtCore.QRect(0, 0, 961, 1061))
        font = QtGui.QFont()
        font.setFamily("Newsreader")
        font.setPointSize(50)
        self.videoButton.setFont(font)
        self.videoButton.setStyleSheet("background-color: #D9D9D9;\n"
"color: #426B1F;")
        self.videoButton.setObjectName("videoButton")
        self.textButton = QtWidgets.QPushButton(self.centralwidget)
        self.textButton.setGeometry(QtCore.QRect(960, 0, 960, 1061))
        font = QtGui.QFont()
        font.setFamily("Newsreader")
        font.setPointSize(50)
        self.textButton.setFont(font)
        self.textButton.setStyleSheet("background-color: #426B1F;\n"
"color: #D9D9D9;\n"
"")
        self.textButton.setObjectName("textButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1920, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Live Emotion Detection"))
        self.videoButton.setText(_translate("MainWindow", "VIDEO"))
        self.textButton.setText(_translate("MainWindow", "TEXT"))
