# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'app.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_videoWindow(object):
    def setupUi(self, videoWindow):
        videoWindow.setObjectName("videoWindow")
        videoWindow.resize(1920, 1080)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        videoWindow.setFont(font)
        videoWindow.setMouseTracking(True)
        videoWindow.setToolTipDuration(-2)
        videoWindow.setAutoFillBackground(False)
        videoWindow.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"}\n"
"\n"
"\n"
"\n"
"")
        videoWindow.setIconSize(QtCore.QSize(24, 24))
        videoWindow.setAnimated(True)
        videoWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(videoWindow)
        self.centralwidget.setStyleSheet("QWidget {\n"
"    background: #FFFFFF;\n"
"}\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.liveCam = QtWidgets.QGraphicsView(self.centralwidget)
        self.liveCam.setGeometry(QtCore.QRect(880, 220, 960, 540))
        self.liveCam.setMaximumSize(QtCore.QSize(960, 540))
        self.liveCam.setStyleSheet(" background-color: #FFFFFF;\n"
"border: none;\n"
"border-radius: 40px;\n"
"")
        self.liveCam.setObjectName("liveCam")
        self.progressBar_Angry = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar_Angry.setGeometry(QtCore.QRect(30, 220, 821, 80))
        self.progressBar_Angry.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.progressBar_Angry.setAutoFillBackground(False)
        self.progressBar_Angry.setStyleSheet("QProgressBar {\n"
"    border-radius: 40px;\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                stop: 0 #EFEFEF, stop: 1 #D9D9D9);\n"
"    border: 1px solid transparent;\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    background-color: #426B1F;\n"
"    border-radius: 38px;\n"
"    margin: 1px;\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                stop: 0 #497C23, stop: 1 #426B1F);\n"
"}\n"
"\n"
"\n"
"")
        self.progressBar_Angry.setProperty("value", 12)
        self.progressBar_Angry.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.progressBar_Angry.setTextVisible(False)
        self.progressBar_Angry.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar_Angry.setInvertedAppearance(False)
        self.progressBar_Angry.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBar_Angry.setObjectName("progressBar_Angry")
        self.progressBar_Disgust = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar_Disgust.setGeometry(QtCore.QRect(30, 310, 821, 80))
        self.progressBar_Disgust.setFocusPolicy(QtCore.Qt.NoFocus)
        self.progressBar_Disgust.setStyleSheet("QProgressBar {\n"
"    border-radius: 40px;\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                stop: 0 #EFEFEF, stop: 1 #D9D9D9);\n"
"    border: 1px solid transparent;\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    background-color: #426B1F;\n"
"    border-radius: 38px;\n"
"    margin: 1px;\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                stop: 0 #497C23, stop: 1 #426B1F);\n"
"}\n"
"\n"
"\n"
"")
        self.progressBar_Disgust.setProperty("value", 18)
        self.progressBar_Disgust.setTextVisible(False)
        self.progressBar_Disgust.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar_Disgust.setInvertedAppearance(False)
        self.progressBar_Disgust.setTextDirection(QtWidgets.QProgressBar.BottomToTop)
        self.progressBar_Disgust.setObjectName("progressBar_Disgust")
        self.progressBar_Happy = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar_Happy.setGeometry(QtCore.QRect(30, 490, 821, 80))
        self.progressBar_Happy.setStyleSheet("QProgressBar {\n"
"    border-radius: 40px;\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                stop: 0 #EFEFEF, stop: 1 #D9D9D9);\n"
"    border: 1px solid transparent;\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    background-color: #426B1F;\n"
"    border-radius: 38px;\n"
"    margin: 1px;\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                stop: 0 #497C23, stop: 1 #426B1F);\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.progressBar_Happy.setProperty("value", 10)
        self.progressBar_Happy.setTextVisible(False)
        self.progressBar_Happy.setObjectName("progressBar_Happy")
        self.progressBar_Fear = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar_Fear.setEnabled(True)
        self.progressBar_Fear.setGeometry(QtCore.QRect(30, 400, 821, 80))
        self.progressBar_Fear.setAutoFillBackground(False)
        self.progressBar_Fear.setStyleSheet("QProgressBar {\n"
"    border-radius: 40px;\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                stop: 0 #EFEFEF, stop: 1 #D9D9D9);\n"
"    border: 1px solid transparent;\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    background-color: #426B1F;\n"
"    border-radius: 38px;\n"
"    margin: 1px;\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                stop: 0 #497C23, stop: 1 #426B1F);\n"
"}\n"
"\n"
"\n"
"")
        self.progressBar_Fear.setProperty("value", 55)
        self.progressBar_Fear.setTextVisible(False)
        self.progressBar_Fear.setObjectName("progressBar_Fear")
        self.progressBar_Sad = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar_Sad.setGeometry(QtCore.QRect(30, 580, 821, 80))
        self.progressBar_Sad.setStyleSheet("QProgressBar {\n"
"    border-radius: 40px;\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                stop: 0 #EFEFEF, stop: 1 #D9D9D9);\n"
"    border: 1px solid transparent;\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    background-color: #426B1F;\n"
"    border-radius: 38px;\n"
"    margin: 1px;\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                stop: 0 #497C23, stop: 1 #426B1F);\n"
"}\n"
"\n"
"\n"
"")
        self.progressBar_Sad.setProperty("value", 0)
        self.progressBar_Sad.setTextVisible(False)
        self.progressBar_Sad.setObjectName("progressBar_Sad")
        self.progressBar_Surprise = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar_Surprise.setGeometry(QtCore.QRect(30, 670, 821, 80))
        self.progressBar_Surprise.setStyleSheet("QProgressBar {\n"
"    border-radius: 40px;\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                stop: 0 #EFEFEF, stop: 1 #D9D9D9);\n"
"    border: 1px solid transparent;\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    background-color: #426B1F;\n"
"    border-radius: 38px;\n"
"    margin: 1px;\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                stop: 0 #497C23, stop: 1 #426B1F);\n"
"}\n"
"\n"
"\n"
"")
        self.progressBar_Surprise.setProperty("value", 11)
        self.progressBar_Surprise.setTextVisible(False)
        self.progressBar_Surprise.setObjectName("progressBar_Surprise")
        self.progressBar_Neutral = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar_Neutral.setGeometry(QtCore.QRect(30, 760, 821, 80))
        self.progressBar_Neutral.setStyleSheet("QProgressBar {\n"
"    border-radius: 40px;\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                stop: 0 #EFEFEF, stop: 1 #D9D9D9);\n"
"    border: 1px solid transparent;\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    background-color: #426B1F;\n"
"    border-radius: 38px;\n"
"    margin: 1px;\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                stop: 0 #497C23, stop: 1 #426B1F);\n"
"}\n"
"\n"
"")
        self.progressBar_Neutral.setProperty("value", 11)
        self.progressBar_Neutral.setTextVisible(False)
        self.progressBar_Neutral.setObjectName("progressBar_Neutral")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(180, 150, 501, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser.sizePolicy().hasHeightForWidth())
        self.textBrowser.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Newsreader")
        font.setBold(False)
        font.setWeight(50)
        self.textBrowser.setFont(font)
        self.textBrowser.setStyleSheet("background: transparent;\n"
"border: none;\n"
"color: #426B1F;\n"
"")
        self.textBrowser.setObjectName("textBrowser")
        self.statusText = QtWidgets.QTextBrowser(self.centralwidget)
        self.statusText.setGeometry(QtCore.QRect(870, 770, 501, 261))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statusText.sizePolicy().hasHeightForWidth())
        self.statusText.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Newsreader")
        font.setPointSize(72)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.statusText.setFont(font)
        self.statusText.setStyleSheet("background: transparent;\n"
"border: none;\n"
"color: #426B1F;\n"
"")
        self.statusText.setObjectName("statusText")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(50, 40, 501, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser_2.sizePolicy().hasHeightForWidth())
        self.textBrowser_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Newsreader")
        font.setBold(False)
        font.setWeight(50)
        self.textBrowser_2.setFont(font)
        self.textBrowser_2.setStyleSheet("background: transparent;\n"
"border: none;\n"
"color: #426B1F;\n"
"")
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.textBrowser_5 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_5.setGeometry(QtCore.QRect(35, 245, 91, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser_5.sizePolicy().hasHeightForWidth())
        self.textBrowser_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Newsreader")
        font.setBold(False)
        font.setWeight(50)
        self.textBrowser_5.setFont(font)
        self.textBrowser_5.setStyleSheet("background: transparent;\n"
"border: none;\n"
"color: #FFFFFF;\n"
"")
        self.textBrowser_5.setObjectName("textBrowser_5")
        self.textBrowser_6 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_6.setGeometry(QtCore.QRect(35, 335, 91, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser_6.sizePolicy().hasHeightForWidth())
        self.textBrowser_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Newsreader")
        font.setBold(False)
        font.setWeight(50)
        self.textBrowser_6.setFont(font)
        self.textBrowser_6.setStyleSheet("background: transparent;\n"
"border: none;\n"
"color: #FFFFFF;\n"
"")
        self.textBrowser_6.setObjectName("textBrowser_6")
        self.textBrowser_7 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_7.setGeometry(QtCore.QRect(35, 425, 91, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser_7.sizePolicy().hasHeightForWidth())
        self.textBrowser_7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Newsreader")
        font.setBold(False)
        font.setWeight(50)
        self.textBrowser_7.setFont(font)
        self.textBrowser_7.setStyleSheet("background: transparent;\n"
"border: none;\n"
"color: #FFFFFF;\n"
"")
        self.textBrowser_7.setObjectName("textBrowser_7")
        self.textBrowser_8 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_8.setGeometry(QtCore.QRect(35, 515, 91, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser_8.sizePolicy().hasHeightForWidth())
        self.textBrowser_8.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Newsreader")
        font.setBold(False)
        font.setWeight(50)
        self.textBrowser_8.setFont(font)
        self.textBrowser_8.setStyleSheet("background: transparent;\n"
"border: none;\n"
"color: #FFFFFF;\n"
"")
        self.textBrowser_8.setObjectName("textBrowser_8")
        self.textBrowser_9 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_9.setGeometry(QtCore.QRect(35, 605, 91, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser_9.sizePolicy().hasHeightForWidth())
        self.textBrowser_9.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Newsreader")
        font.setBold(False)
        font.setWeight(50)
        self.textBrowser_9.setFont(font)
        self.textBrowser_9.setStyleSheet("background: transparent;\n"
"border: none;\n"
"color: #FFFFFF;\n"
"")
        self.textBrowser_9.setObjectName("textBrowser_9")
        self.textBrowser_10 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_10.setGeometry(QtCore.QRect(35, 695, 91, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser_10.sizePolicy().hasHeightForWidth())
        self.textBrowser_10.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Newsreader")
        font.setBold(False)
        font.setWeight(50)
        self.textBrowser_10.setFont(font)
        self.textBrowser_10.setStyleSheet("background: transparent;\n"
"border: none;\n"
"color: #FFFFFF;\n"
"")
        self.textBrowser_10.setObjectName("textBrowser_10")
        self.textBrowser_11 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_11.setGeometry(QtCore.QRect(35, 785, 91, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser_11.sizePolicy().hasHeightForWidth())
        self.textBrowser_11.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Newsreader")
        font.setBold(False)
        font.setWeight(50)
        self.textBrowser_11.setFont(font)
        self.textBrowser_11.setStyleSheet("background: transparent;\n"
"border: none;\n"
"color: #FFFFFF;\n"
"")
        self.textBrowser_11.setObjectName("textBrowser_11")
        self.emotionDetectorButton = QtWidgets.QPushButton(self.centralwidget)
        self.emotionDetectorButton.setGeometry(QtCore.QRect(1350, 40, 141, 51))
        font = QtGui.QFont()
        font.setFamily("Newsreader")
        font.setPointSize(13)
        self.emotionDetectorButton.setFont(font)
        self.emotionDetectorButton.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"}")
        self.emotionDetectorButton.setObjectName("emotionDetectorButton")
        self.whoWeAreButton = QtWidgets.QPushButton(self.centralwidget)
        self.whoWeAreButton.setGeometry(QtCore.QRect(1530, 40, 101, 51))
        font = QtGui.QFont()
        font.setFamily("Newsreader")
        font.setPointSize(13)
        self.whoWeAreButton.setFont(font)
        self.whoWeAreButton.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"}\n"
"")
        self.whoWeAreButton.setObjectName("whoWeAreButton")
        self.backButton = QtWidgets.QPushButton(self.centralwidget)
        self.backButton.setGeometry(QtCore.QRect(1710, 40, 131, 61))
        font = QtGui.QFont()
        font.setFamily("Newsreader")
        font.setPointSize(15)
        self.backButton.setFont(font)
        self.backButton.setStyleSheet("QPushButton {\n"
"    background-color: #426B1F;\n"
"    color: white;\n"
"    border-radius: 30px;\n"
"    padding: 5px 20px;\n"
"}")
        self.backButton.setObjectName("backButton")
        videoWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(videoWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1920, 21))
        self.menubar.setObjectName("menubar")
        videoWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(videoWindow)
        self.statusbar.setObjectName("statusbar")
        videoWindow.setStatusBar(self.statusbar)

        self.retranslateUi(videoWindow)
        QtCore.QMetaObject.connectSlotsByName(videoWindow)

    def retranslateUi(self, videoWindow):
        _translate = QtCore.QCoreApplication.translate
        videoWindow.setWindowTitle(_translate("videoWindow", "Live Emotion Detection"))
        self.progressBar_Disgust.setFormat(_translate("videoWindow", "%p%"))
        self.textBrowser.setHtml(_translate("videoWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Newsreader\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:24pt;\">Emotion Rates</span></p></body></html>"))
        self.statusText.setHtml(_translate("videoWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Newsreader\'; font-size:72pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">NEUTRAL</p></body></html>"))
        self.textBrowser_2.setHtml(_translate("videoWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Newsreader\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:28pt;\">Video Detector</span></p></body></html>"))
        self.textBrowser_5.setHtml(_translate("videoWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Newsreader\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Inter\'; font-size:11pt;\">ANGRY</span></p></body></html>"))
        self.textBrowser_6.setHtml(_translate("videoWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Newsreader\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Inter\'; font-size:11pt;\">DISGUST</span></p></body></html>"))
        self.textBrowser_7.setHtml(_translate("videoWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Newsreader\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Inter\'; font-size:11pt;\">FEAR</span></p></body></html>"))
        self.textBrowser_8.setHtml(_translate("videoWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Newsreader\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Inter\'; font-size:11pt;\">HAPPY</span></p></body></html>"))
        self.textBrowser_9.setHtml(_translate("videoWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Newsreader\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Inter\'; font-size:11pt;\">SAD</span></p></body></html>"))
        self.textBrowser_10.setHtml(_translate("videoWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Newsreader\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Inter\'; font-size:11pt;\">SURPRISE</span></p></body></html>"))
        self.textBrowser_11.setHtml(_translate("videoWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Newsreader\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Inter\'; font-size:11pt;\">NEUTRAL</span></p></body></html>"))
        self.emotionDetectorButton.setText(_translate("videoWindow", "Emotion Detector"))
        self.whoWeAreButton.setText(_translate("videoWindow", "Who we are"))
        self.backButton.setText(_translate("videoWindow", "BACK"))
