# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'whoweare.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_whoweareWindow(object):
    def setupUi(self, whoweareWindow):
        whoweareWindow.setObjectName("whoweareWindow")
        whoweareWindow.resize(1920, 1080)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        whoweareWindow.setFont(font)
        whoweareWindow.setMouseTracking(True)
        whoweareWindow.setToolTipDuration(-2)
        whoweareWindow.setAutoFillBackground(False)
        whoweareWindow.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"}\n"
"\n"
"\n"
"\n"
"")
        whoweareWindow.setIconSize(QtCore.QSize(24, 24))
        whoweareWindow.setAnimated(True)
        whoweareWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(whoweareWindow)
        self.centralwidget.setStyleSheet("QWidget {\n"
"    background: #FFFFFF;\n"
"}\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.videoButton = QtWidgets.QPushButton(self.centralwidget)
        self.videoButton.setGeometry(QtCore.QRect(630, 860, 191, 71))
        font = QtGui.QFont()
        font.setFamily("Newsreader")
        font.setPointSize(15)
        self.videoButton.setFont(font)
        self.videoButton.setStyleSheet("QPushButton {\n"
"    background-color: #426B1F;\n"
"    color: white;\n"
"    border-radius: 30px;\n"
"    padding: 5px 20px;\n"
"}")
        self.videoButton.setObjectName("videoButton")
        self.emotionButton = QtWidgets.QPushButton(self.centralwidget)
        self.emotionButton.setGeometry(QtCore.QRect(1050, 860, 191, 71))
        font = QtGui.QFont()
        font.setFamily("Newsreader")
        font.setPointSize(15)
        self.emotionButton.setFont(font)
        self.emotionButton.setStyleSheet("QPushButton {\n"
"    background-color: #426B1F;\n"
"    color: white;\n"
"    border-radius: 30px;\n"
"    padding: 5px 20px;\n"
"}")
        self.emotionButton.setObjectName("emotionButton")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(10, 100, 1891, 651))
        font = QtGui.QFont()
        font.setFamily("Newsreader")
        font.setPointSize(20)
        self.textBrowser.setFont(font)
        self.textBrowser.setStyleSheet("background: transparent;\n"
"border: none;\n"
"color: #426B1F;")
        self.textBrowser.setObjectName("textBrowser")
        whoweareWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(whoweareWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1920, 21))
        self.menubar.setObjectName("menubar")
        whoweareWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(whoweareWindow)
        self.statusbar.setObjectName("statusbar")
        whoweareWindow.setStatusBar(self.statusbar)

        self.retranslateUi(whoweareWindow)
        QtCore.QMetaObject.connectSlotsByName(whoweareWindow)

    def retranslateUi(self, whoweareWindow):
        _translate = QtCore.QCoreApplication.translate
        whoweareWindow.setWindowTitle(_translate("whoweareWindow", "Live Emotion Detection"))
        self.videoButton.setText(_translate("whoweareWindow", "Video Detector"))
        self.emotionButton.setText(_translate("whoweareWindow", "Emotion Detector"))
        self.textBrowser.setHtml(_translate("whoweareWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Newsreader\'; font-size:20pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:48pt;\">EMİRCAN DURMUŞ (CMPE)</span></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:48pt;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:48pt;\">ALP KARAKULLUKÇU (CMPE)</span></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:48pt;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:48pt;\">EMİNE ESRA KOPTUR (CMPE)</span></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:48pt;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:48pt;\">HARUN SEVİNÇ (CMPE)</span></p></body></html>"))
